# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2ec66b3a97c17ee02deba8af865b5f0d74f57446b1e2f45bc9cc91f71a5865718959be1e6241d7340a81232f3c2ab854ca88cd9cb9f9bb3ad581bee17a0138d4

test:
  secret_key_base: 689132f51509557d5094a1494794e5236676e3c7d0d970749c801ac78667e33f493ed4d8c358ad004ff94d39f7029b2a259ca5685d3e94971d39e2cfcb020b53

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
